### ISSUE TITLE
New AKS Mariner nodes are missing 10-azure.conflist CNI config

### ISSUE THREAD

**Issue by james-bjss** [Azure/AgentBaker#4499] opened 2024-06-11 10:39 UTC
**What happened**:
Since updating our AKS nodes to `AKSCBLMariner-V2gen2-202405.20.0` we observed that the CNI conflist file `/etc/cni/net.d/10-azure.conflist` is no longer present on the new nodes.

This breaks other CNIs which chain to this as the file is not present. We suspect that the base image previously created this file and recent updates have changed this behaviour.

**What you expected to happen**:
New nodes should have the `/etc/cni/net.d/10-azure.conflist` present on boot.

**How to reproduce it**:
Updated nodes from `AKSCBLMariner-V2gen2-202402.07.0` -> `AKSCBLMariner-V2gen2-202405.20.0`
Remote into machine and observe  `/etc/cni/net.d/10-azure.conflist` is absent.

**Anything else we need to know?**:
Previously the file was present on `AKSCBLMariner-V2gen2-202312.06.0` so the change occurred between these two versions.
Some examples of the azure-cns deamonset have the `dropz` initcontainer argument create this file; however this is not present on our clusters (both with and without the new images).

**Environment**:

- AgentBaker version: AKSCBLMariner-V2gen2-202405.20.0
- Kubernetes version (use `kubectl version`): 1.27.9

**Comment by james-bjss** [comment] 2024-06-11 10:42
Would anyone be able to help track down why the conflist file is missing? It seems there was some process previously which was baking this into the base images and it has since been removed. Diffing the repo shows 1000's of changes between those releases so it's difficult to track down where exactly the change happened.

It's not clear if this is intentional and dropz shoudl be generating this file instead (it doesn't with the current daemonset config). Or if thsi file is now deprecated for `15-azure-swift.conflist`?

**Comment by djsly** [comment] 2024-10-11 13:42
Closing as duplicate of [Azure/AKS#4349](https://github.com/Azure/AKS/issues/4349)

**Closed by djsly** 2024-10-11 13:42 UTC
